/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class run_halo_liquid_utils_CPUWatchDog */

#ifndef _Included_run_halo_liquid_utils_CPUWatchDog
#define _Included_run_halo_liquid_utils_CPUWatchDog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     run_halo_liquid_utils_CPUWatchDog
 * Method:    getCPULoad
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_run_halo_liquid_utils_CPUWatchDog_getCPULoad
  (JNIEnv *, jobject, jint);

/*
 * Class:     run_halo_liquid_utils_CPUWatchDog
 * Method:    getBatchCPULoad
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_run_halo_liquid_utils_CPUWatchDog_getBatchCPULoad
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
